import {
    Geist,
    Geist_Mono,
    Inter,
    Nanum_Gothic_Coding,
    Roboto,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const nanumGothicCoding = Nanum_Gothic_Coding({
    variable: "--font-nanum-gothic-coding",
    weight: "400",
    subsets: ["latin"],
});

const verdana = Roboto({
    variable: "--font-verdana",
    weight: "400",
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${nanumGothicCoding.variable} ${verdana.variable} font-sans`}
            >
                {children}
            </body>
        </html>
    );
}
